---
name: "[Ask a new question here.]"
title: 'Ask your question using the issue title'
description: 'Ask me anything"
labels: needs-answer
assignees: bdougie
body:
- type: dropdown
  attributes:
    label: Category
    description: How would you categorize this question?
    multiple: true
    options:
      - Career
      - GitHub
      - JavaScript
      - Other
  validations:
    required: true
- type: textarea
  attributes:
    label: More context
    description: If you have links or more context you would like to share, please do so here?
  validations:
    required: false
